export const ADD_TO_WATCHLIST = "ADD_TO_WATCHLIST";

export const REMOVE_FROM_WATCHLIST = "REMOVE_FROM_WATCHLIST";
export const UPDATE_MOVIES = "UPDATE_MOVIES";

export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";
